### ISSUE TITLE
Compilation Issues with 'Ma et al.' method in matlab 2016b linux 

### ISSUE THREAD

**Issue by waleedgondal** [roimehrez/PIRM2018#1]
Hi, I am trying to run the evaluation script in matlab 2016b linux version. I am having issues in running Ma et al. script. I have successfully created MEX for linux and copied the files in ```utils/sr-metric-master/external/matlabPyrTools```. Upon running ```evaluate_results.m```, I get an error stating  ```Undefined function or variable 'mexRF_predict'.```
I think that the method requires a linux-built mex file for ```mexRF_predict``` located in ```  utils/sr-metric-master/external/randomforest-matlab/RF_Reg_C``` where mex file for windows is given. Luckily, there is a `compile_linux.m` to compile mex for linux however it gives the following compilation error. I don't think it's a gcc version issue as previous mex file got compiled with the same warning.

>> compile_linux
rm: cannot remove '*.mexglx': No such file or directory
rm: cannot remove '*.mexa64': No such file or directory
rm -rf *.mexa64 *.mexglx *.mexw32 *.o src/*.o tempbuild/*.o *.exe *~ gmon* diabetes_test cokus_test a.out
echo 'deleted mex files, object files, gmon files and diabetes_test'
deleted mex files, object files, gmon files and diabetes_test
echo -e 'Making mex'
Making mex
#matlab-mex src/cokus.cpp src/mex_regressionRF_train.cpp src/reg_RF.cpp -output mexRF_train -DMATLAB 
matlab-mex src/cokus.cpp src/mex_regressionRF_predict.cpp src/reg_RF.cpp -output mexRF_predict -DMATLAB 
Building with 'g++'.
Warning: You are using gcc version '5.4.0'. The version of gcc is not supported. The version currently supported with MEX is '4.9.x'. For a list of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
[$HOME]/PIRM2018/utils/sr-metric-master/external/randomforest-matlab/RF_Reg_C/src/mex_regressionRF_predict.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
[$HOME]/PIRM2018/utils/sr-metric-master/external/randomforest-matlab/RF_Reg_C/src/mex_regressionRF_predict.cpp:82:57: error: invalid conversion from ‘int’ to ‘mxComplexity’ [-fpermissive]
  plhs[0]=mxCreateNumericMatrix(n_size,1,mxDOUBLE_CLASS,0);
                                                         ^
In file included from [$HOME]/matlab/linux/R2016b/extern/include/mex.h:51:0,
                 from [$HOME]/PIRM2018/utils/sr-metric-master/external/randomforest-matlab/RF_Reg_C/src/mex_regressionRF_predict.cpp:43:
[$HOME]/matlab/linux/R2016b/extern/include/matrix.h:741:1: note:   initializing argument 4 of ‘mxArray* mxCreateNumericMatrix_700(int, int, mxClassID, mxComplexity)’
 mxCreateNumericMatrix_700(int m, int n, mxClassID classid, mxComplexity flag);
 ^
Makefile:44: recipe for target 'mex' failed
make: *** [mex] Error 255

 I understand it's not your code, however I was wondering if you ran into this issue or you tried to run the code on linux's latest version?

**Comment by roimehrez** [comment]
change line 82
`plhs[0]=mxCreateNumericMatrix(n_size,1,mxDOUBLE_CLASS,0);`
to
`plhs[0]=mxCreateNumericMatrix(n_size,1,mxDOUBLE_CLASS,mxREAL);`

Pre-compile mex files (for OS, Linux and Win) are also available in this [link ](https://www.dropbox.com/s/edm76nhxhiouezu/RF_Reg_C.zip?dl=0)

**Comment by waleedgondal** [comment]
It worked, thanks!

**Comment by Timmate** [comment]
As a note, to run *compile_linux.m* even after applying the above-mentioned change for line 82, in my case I had to provide the full path to mex instead of just `make mex`, like [here][1].

[1]: https://github.com/Timmate/sr-metric-fixed-for-linux/blob/330bf93619a522776f383093a5ac6d387ff95b86/external/randomforest-matlab/RF_Reg_C/compile_linux.m#L23
